2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_setup.py:_flush():67] Configure stats pid to 981104
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_setup.py:_flush():67] Loading settings from /home/mwahlin/.config/wandb/settings
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_setup.py:_flush():67] Loading settings from /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/settings
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/run-20250425_202528-rwmi5fll/logs/debug.log
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/run-20250425_202528-rwmi5fll/logs/debug-internal.log
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_init.py:init():761] calling init triggers
2025-04-25 20:25:28,695 INFO    MainThread:981104 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-25 20:25:28,696 INFO    MainThread:981104 [wandb_init.py:init():784] starting backend
2025-04-25 20:25:28,696 INFO    MainThread:981104 [wandb_init.py:init():788] sending inform_init request
2025-04-25 20:25:28,722 INFO    MainThread:981104 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-25 20:25:28,725 INFO    MainThread:981104 [wandb_init.py:init():803] backend started and connected
2025-04-25 20:25:28,729 INFO    MainThread:981104 [wandb_init.py:init():896] updated telemetry
2025-04-25 20:25:28,742 INFO    MainThread:981104 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-25 20:25:29,135 INFO    MainThread:981104 [wandb_init.py:init():995] starting run threads in backend
2025-04-25 20:25:29,498 INFO    MainThread:981104 [wandb_run.py:_console_start():2377] atexit reg
2025-04-25 20:25:29,498 INFO    MainThread:981104 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-25 20:25:29,498 INFO    MainThread:981104 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-25 20:25:29,499 INFO    MainThread:981104 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-25 20:25:29,504 INFO    MainThread:981104 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-25 20:25:29,506 INFO    MainThread:981104 [wandb_run.py:_config_callback():1261] config_cb None None {}
2025-04-26 02:29:09,727 WARNING MsgRouterThr:981104 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-26 02:29:09,735 INFO    MsgRouterThr:981104 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
